openapi: 3.0.0
info:
  title: Trello Clone API
  description: Backend for a simple Trello clone application
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from login endpoint
  schemas:
    Board:
      type: object
      required:
        - name
      properties:
        id:
          type: string
        name:
          type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
    List:
      type: object
      required:
        - title
        - boardId
      properties:
        id:
          type: string
        boardId:
          type: string
        userId:
          type: string
        title:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Card:
      type: object
      required:
        - title
        - listId
      properties:
        id:
          type: string
        listId:
          type: string
        userId:
          type: string
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password
    LoginResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWT token for authentication
    User:
      type: object
      required:
        - username
      properties:
        id:
          type: string
        username:
          type: string
        createdAt:
          type: string
          format: date-time
    RegisterRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 30
        password:
          type: string
          minLength: 6
          format: password
    LogoutResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

security:
  - bearerAuth: []

paths:
  /login:
    post:
      security: []  # No authentication required for login
      summary: Login to get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /logout:
    post:
      security:
        - bearerAuth: []
      summary: Logout and revoke current token
      responses:
        '200':
          description: Successfully logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /register:
    post:
      security: []
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Username already taken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      security:
        - bearerAuth: []
      summary: Get all users
      description: Returns a list of all users (without passwords)
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /boards:
    get:
      security:
        - bearerAuth: []  # Require authentication for GET
      summary: Get all boards
      responses:
        200:
          description: A list of boards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      security:
        - bearerAuth: []
      summary: Create a new board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
      responses:
        201:
          description: Board created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'

  /boards/{boardId}:
    get:
      security:
        - bearerAuth: []  # Require authentication for GET
      summary: Get a specific board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Board retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden - Not authorized to view this board
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      security:
        - bearerAuth: []  # Require authentication for PUT
      summary: Update a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: Board updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      responses:
        204:
          description: Board deleted successfully

  /boards/{boardId}/lists:
    get:
      security:
        - bearerAuth: []  # Require authentication for GET
      summary: Get all lists for a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lists retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/List'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden - Not authorized to view this board's lists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      security:
        - bearerAuth: []  # Require authentication for POST
      summary: Create a new list
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        201:
          description: List created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'

  /lists/{listId}:
    get:
      security: []  # No authentication required for GET
      summary: Get a specific list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
    put:
      security:
        - bearerAuth: []
      summary: Update a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 100
                boardId:
                  type: string
      responses:
        200:
          description: List updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      responses:
        204:
          description: List deleted successfully

  /lists/{listId}/cards:
    get:
      security:
        - bearerAuth: []  # Require authentication for GET
      summary: Get all cards in a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Cards retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden - Not authorized to view cards in this list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      security:
        - bearerAuth: []  # Require authentication for POST
      summary: Create a new card
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: Card created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'

  /cards/{cardId}:
    get:
      security:
        - bearerAuth: []  # Require authentication for GET
      summary: Get a specific card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Card retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden - Not authorized to view this card
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      security:
        - bearerAuth: []  # Require authentication for PUT
      summary: Update a card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                listId:
                  type: string
      responses:
        200:
          description: Card updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      responses:
        204:
          description: Card deleted successfully

  /cards/{cardId}/move:
    patch:
      security:
        - bearerAuth: []
      summary: Move a card to a different list
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - listId
              properties:
                listId:
                  type: string
                position:
                  type: number
                  minimum: 0
      responses:
        200:
          description: Card moved successfully 