openapi: 3.0.0
info:
  title: Trello Clone API
  description: Backend for a simple Trello clone application
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Board:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    List:
      type: object
      properties:
        id:
          type: string
        boardId:
          type: string
        title:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Card:
      type: object
      properties:
        id:
          type: string
        listId:
          type: string
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        error:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string

security:
  - bearerAuth: []

paths:
  /api/v1/login:
    post:
      security: []  # No authentication required for login
      summary: Login to get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/boards:
    get:
      security: []  # No authentication required for GET
      summary: Get all boards
      responses:
        200:
          description: A list of boards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
    post:
      security:
        - bearerAuth: []  # Require authentication for POST
      summary: Create a new board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        201:
          description: Board created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'

  /api/v1/boards/{boardId}:
    get:
      security: []  # No authentication required for GET
      summary: Get a specific board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
    put:
      security:
        - bearerAuth: []  # Require authentication for PUT
      summary: Update a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: Board updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      responses:
        204:
          description: Board deleted successfully

  /api/v1/boards/{boardId}/lists:
    get:
      security: []  # No authentication required for GET
      summary: Get all lists for a board
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
    post:
      security:
        - bearerAuth: []  # Require authentication for POST
      summary: Create a new list
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        201:
          description: List created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'

  /api/v1/lists/{listId}:
    get:
      security: []  # No authentication required for GET
      summary: Get a specific list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
    put:
      security:
        - bearerAuth: []  # Require authentication for PUT
      summary: Update a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                boardId:
                  type: string
      responses:
        200:
          description: List updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      responses:
        204:
          description: List deleted successfully

  /api/v1/lists/{listId}/cards:
    get:
      security: []  # No authentication required for GET
      summary: Get all cards in a list
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
    post:
      security:
        - bearerAuth: []  # Require authentication for POST
      summary: Create a new card
      parameters:
        - in: path
          name: listId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: Card created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'

  /api/v1/cards/{cardId}:
    get:
      security: []  # No authentication required for GET
      summary: Get a specific card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
    put:
      security:
        - bearerAuth: []  # Require authentication for PUT
      summary: Update a card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                listId:
                  type: string
      responses:
        200:
          description: Card updated successfully
    delete:
      security:
        - bearerAuth: []  # Require authentication for DELETE
      summary: Delete a card
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      responses:
        204:
          description: Card deleted successfully

  /api/v1/cards/{cardId}/move:
    patch:
      security:
        - bearerAuth: []  # Require authentication for PATCH
      summary: Move a card to a different list
      parameters:
        - in: path
          name: cardId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listId:
                  type: string
                position:
                  type: number
      responses:
        200:
          description: Card moved successfully 